### PR TITLE
How to stay safe (first draft)

### PR DESCRIPTION
**Pull request by 409H**
* Added security article on tips of how to stay safe during ICOs - _first draft_

### CODE REVIEW

**Comment by tayvano** [comment]
@409H Is this done? Need some help on it?

**Comment by 409H** [comment]
@tayvano will be finishing it up this week, but feel free to note some things down you want to see in it

**Comment by tayvano** [comment]
@409H I like it as is. Jordan might have some feedback on it, but I think its strong and timely and we should definitely get it live at some point and tweet it out!

**Comment by tayvano** [comment]
@409H PING 🏓

**Comment by jspence425** [comment]
👍 from me.

**Pull request merged**
